In [2]:
graphics_toolkit ("gnuplot"); % required

Carregando as matrizes em memória:

In [3]:
load trab1/arquivos/bcsstk01
b01 = Problem.A;
load trab1/arquivos/plat362
p362 = Problem.A;
load trab1/arquivos/bcsstk15
b15 = Problem.A;

## a) Exibindo dados das matrizes

In [4]:
dim_b01 = size(b01)
dim_p362 = size(p362)
dim_b15 = size(b15)

norm_b01 = norm(b01)
norm_p362 = norm(p362)
norm_b15 = norm(b15)

cond_b01 = cond(b01)
cond_p362 = cond(p362)
cond_b15 = cond(b15)

dim_b01 =

   48   48

dim_p362 =

   362   362

dim_b15 =

   3948   3948

norm_b01 = 3.0152e+09
norm_p362 = 0.7743




## b) Decompondo as matrizes:

In [5]:
[b01L, b01U, _, _] = lu(b01);
[p362L, p362U, _, _] = lu(p362);
[b15L, b15U, _, _] = lu(b15);

[Errno 9] Bad file descriptor
[Errno 9] Bad file descriptor


Exibindo a configuração das matrizes:

In [ ]:
spy(b01, 10, ".")

In [ ]:
spy(b01L, 10, ".")

In [ ]:
spy(b01U, 10, ".")

In [ ]:
spy(p362, 1, ".")

In [ ]:
spy(p362L, 1, ".")

In [ ]:
spy(p362U, 1, ".")

In [ ]:
spy(b15, 1, ".")

In [ ]:
spy(b15L, 1, ".")

In [ ]:
spy(b15U, 1, ".")

## c) Calculando as taxas de preenchimento:

In [ ]:
function tx = taxa_preenchimento(A, L, U)
    tx = 100 - 100 * nnz(A) / ( nnz(L) + nnz(U) );
endfunction

taxa_preenchimento_b01 = taxa_preenchimento(b01, b01L, b01U)
taxa_preenchimento_p362 = taxa_preenchimento(p362, p362L, p362U)
taxa_preenchimento_b15 = taxa_preenchimento(b15, b15L, b15U)

## d) Calculando normal do erro e normas do resíduo, para a solução obtida por método de Gauss:

In [ ]:
function norma = norma_erro(A, x)
    norma = norm(ones(rows(A), 1) - x, inf);
endfunction

function norma = norma_residuo(A, b, x)
    norma = norm(b - A * x, inf);
endfunction

b01b = b01 * ones(rows(b01), 1);
p362b = p362 * ones(rows(p362), 1);
b15b = b15 * ones(rows(b15), 1);

b01x = b01\b01b;
p362x = p362\p362b;
b15x = b15\b15b;

norma_erro_b01 = norma_erro(b01, b01b)
norma_erro_p362 = norma_erro(p362, p362b)
norma_erro_b15 = norma_erro(b15, b15b)

norma_residuo_b01 = norma_erro(b01, b01b)
norma_residuo_p362 = norma_erro(p362, p362b)
norma_residuo_b15 = norma_erro(b15, b15b)

% b01_cond = 